version: '3.8'

services:
  backend:
    build: ./backend
    image: my-backend:1.0
    ports:
      - "5050:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=userdb
      - DB_USER=anuj
      - DB_PASSWORD=anuj123

  frontend:
    build: ./frontend
    image: my-frontend:1.0
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: anuj
      POSTGRES_PASSWORD: anuj123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
