apiVersion: v1
kind: Service
metadata:
  name: frontend-service     # Name of the service
spec:
  selector:
    app: frontend            # Matches the label in your frontend deployment
  ports:
    - protocol: TCP
      port: 3000             # The port other services inside the cluster will use
      targetPort: 3000       # The port exposed by the frontend container
  type: ClusterIP            # Default internal-only service
